// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// DNSAnnotationLister helps list DNSAnnotations.
// All objects returned here must be treated as read-only.
type DNSAnnotationLister interface {
	// List lists all DNSAnnotations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DNSAnnotation, err error)
	// DNSAnnotations returns an object that can list and get DNSAnnotations.
	DNSAnnotations(namespace string) DNSAnnotationNamespaceLister
	DNSAnnotationListerExpansion
}

// dNSAnnotationLister implements the DNSAnnotationLister interface.
type dNSAnnotationLister struct {
	listers.ResourceIndexer[*v1alpha1.DNSAnnotation]
}

// NewDNSAnnotationLister returns a new DNSAnnotationLister.
func NewDNSAnnotationLister(indexer cache.Indexer) DNSAnnotationLister {
	return &dNSAnnotationLister{listers.New[*v1alpha1.DNSAnnotation](indexer, v1alpha1.Resource("dnsannotation"))}
}

// DNSAnnotations returns an object that can list and get DNSAnnotations.
func (s *dNSAnnotationLister) DNSAnnotations(namespace string) DNSAnnotationNamespaceLister {
	return dNSAnnotationNamespaceLister{listers.NewNamespaced[*v1alpha1.DNSAnnotation](s.ResourceIndexer, namespace)}
}

// DNSAnnotationNamespaceLister helps list and get DNSAnnotations.
// All objects returned here must be treated as read-only.
type DNSAnnotationNamespaceLister interface {
	// List lists all DNSAnnotations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DNSAnnotation, err error)
	// Get retrieves the DNSAnnotation from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.DNSAnnotation, error)
	DNSAnnotationNamespaceListerExpansion
}

// dNSAnnotationNamespaceLister implements the DNSAnnotationNamespaceLister
// interface.
type dNSAnnotationNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.DNSAnnotation]
}
