// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	dnsv1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DNSEntryLister helps list DNSEntries.
// All objects returned here must be treated as read-only.
type DNSEntryLister interface {
	// List lists all DNSEntries in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dnsv1alpha1.DNSEntry, err error)
	// DNSEntries returns an object that can list and get DNSEntries.
	DNSEntries(namespace string) DNSEntryNamespaceLister
	DNSEntryListerExpansion
}

// dNSEntryLister implements the DNSEntryLister interface.
type dNSEntryLister struct {
	listers.ResourceIndexer[*dnsv1alpha1.DNSEntry]
}

// NewDNSEntryLister returns a new DNSEntryLister.
func NewDNSEntryLister(indexer cache.Indexer) DNSEntryLister {
	return &dNSEntryLister{listers.New[*dnsv1alpha1.DNSEntry](indexer, dnsv1alpha1.Resource("dnsentry"))}
}

// DNSEntries returns an object that can list and get DNSEntries.
func (s *dNSEntryLister) DNSEntries(namespace string) DNSEntryNamespaceLister {
	return dNSEntryNamespaceLister{listers.NewNamespaced[*dnsv1alpha1.DNSEntry](s.ResourceIndexer, namespace)}
}

// DNSEntryNamespaceLister helps list and get DNSEntries.
// All objects returned here must be treated as read-only.
type DNSEntryNamespaceLister interface {
	// List lists all DNSEntries in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*dnsv1alpha1.DNSEntry, err error)
	// Get retrieves the DNSEntry from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*dnsv1alpha1.DNSEntry, error)
	DNSEntryNamespaceListerExpansion
}

// dNSEntryNamespaceLister implements the DNSEntryNamespaceLister
// interface.
type dNSEntryNamespaceLister struct {
	listers.ResourceIndexer[*dnsv1alpha1.DNSEntry]
}
