// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// DNSHostedZonePolicyLister helps list DNSHostedZonePolicies.
// All objects returned here must be treated as read-only.
type DNSHostedZonePolicyLister interface {
	// List lists all DNSHostedZonePolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DNSHostedZonePolicy, err error)
	// DNSHostedZonePolicies returns an object that can list and get DNSHostedZonePolicies.
	DNSHostedZonePolicies(namespace string) DNSHostedZonePolicyNamespaceLister
	DNSHostedZonePolicyListerExpansion
}

// dNSHostedZonePolicyLister implements the DNSHostedZonePolicyLister interface.
type dNSHostedZonePolicyLister struct {
	listers.ResourceIndexer[*v1alpha1.DNSHostedZonePolicy]
}

// NewDNSHostedZonePolicyLister returns a new DNSHostedZonePolicyLister.
func NewDNSHostedZonePolicyLister(indexer cache.Indexer) DNSHostedZonePolicyLister {
	return &dNSHostedZonePolicyLister{listers.New[*v1alpha1.DNSHostedZonePolicy](indexer, v1alpha1.Resource("dnshostedzonepolicy"))}
}

// DNSHostedZonePolicies returns an object that can list and get DNSHostedZonePolicies.
func (s *dNSHostedZonePolicyLister) DNSHostedZonePolicies(namespace string) DNSHostedZonePolicyNamespaceLister {
	return dNSHostedZonePolicyNamespaceLister{listers.NewNamespaced[*v1alpha1.DNSHostedZonePolicy](s.ResourceIndexer, namespace)}
}

// DNSHostedZonePolicyNamespaceLister helps list and get DNSHostedZonePolicies.
// All objects returned here must be treated as read-only.
type DNSHostedZonePolicyNamespaceLister interface {
	// List lists all DNSHostedZonePolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DNSHostedZonePolicy, err error)
	// Get retrieves the DNSHostedZonePolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.DNSHostedZonePolicy, error)
	DNSHostedZonePolicyNamespaceListerExpansion
}

// dNSHostedZonePolicyNamespaceLister implements the DNSHostedZonePolicyNamespaceLister
// interface.
type dNSHostedZonePolicyNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.DNSHostedZonePolicy]
}
