// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// DNSLockLister helps list DNSLocks.
// All objects returned here must be treated as read-only.
type DNSLockLister interface {
	// List lists all DNSLocks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DNSLock, err error)
	// DNSLocks returns an object that can list and get DNSLocks.
	DNSLocks(namespace string) DNSLockNamespaceLister
	DNSLockListerExpansion
}

// dNSLockLister implements the DNSLockLister interface.
type dNSLockLister struct {
	indexer cache.Indexer
}

// NewDNSLockLister returns a new DNSLockLister.
func NewDNSLockLister(indexer cache.Indexer) DNSLockLister {
	return &dNSLockLister{indexer: indexer}
}

// List lists all DNSLocks in the indexer.
func (s *dNSLockLister) List(selector labels.Selector) (ret []*v1alpha1.DNSLock, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.DNSLock))
	})
	return ret, err
}

// DNSLocks returns an object that can list and get DNSLocks.
func (s *dNSLockLister) DNSLocks(namespace string) DNSLockNamespaceLister {
	return dNSLockNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// DNSLockNamespaceLister helps list and get DNSLocks.
// All objects returned here must be treated as read-only.
type DNSLockNamespaceLister interface {
	// List lists all DNSLocks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DNSLock, err error)
	// Get retrieves the DNSLock from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.DNSLock, error)
	DNSLockNamespaceListerExpansion
}

// dNSLockNamespaceLister implements the DNSLockNamespaceLister
// interface.
type dNSLockNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all DNSLocks in the indexer for a given namespace.
func (s dNSLockNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.DNSLock, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.DNSLock))
	})
	return ret, err
}

// Get retrieves the DNSLock from the indexer for a given namespace and name.
func (s dNSLockNamespaceLister) Get(name string) (*v1alpha1.DNSLock, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("dnslock"), name)
	}
	return obj.(*v1alpha1.DNSLock), nil
}
