// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DNSAnnotationListerExpansion allows custom methods to be added to
// DNSAnnotationLister.
type DNSAnnotationListerExpansion interface{}

// DNSAnnotationNamespaceListerExpansion allows custom methods to be added to
// DNSAnnotationNamespaceLister.
type DNSAnnotationNamespaceListerExpansion interface{}

// DNSEntryListerExpansion allows custom methods to be added to
// DNSEntryLister.
type DNSEntryListerExpansion interface{}

// DNSEntryNamespaceListerExpansion allows custom methods to be added to
// DNSEntryNamespaceLister.
type DNSEntryNamespaceListerExpansion interface{}

// DNSHostedZonePolicyListerExpansion allows custom methods to be added to
// DNSHostedZonePolicyLister.
type DNSHostedZonePolicyListerExpansion interface{}

// DNSHostedZonePolicyNamespaceListerExpansion allows custom methods to be added to
// DNSHostedZonePolicyNamespaceLister.
type DNSHostedZonePolicyNamespaceListerExpansion interface{}

// DNSOwnerListerExpansion allows custom methods to be added to
// DNSOwnerLister.
type DNSOwnerListerExpansion interface{}

// DNSOwnerNamespaceListerExpansion allows custom methods to be added to
// DNSOwnerNamespaceLister.
type DNSOwnerNamespaceListerExpansion interface{}

// DNSProviderListerExpansion allows custom methods to be added to
// DNSProviderLister.
type DNSProviderListerExpansion interface{}

// DNSProviderNamespaceListerExpansion allows custom methods to be added to
// DNSProviderNamespaceLister.
type DNSProviderNamespaceListerExpansion interface{}
