{{- if .Values.remoteaccess.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns-management.fullname" . }}-remoteaccess
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.remoteaccess.certs.cacert }}
{{- if .Values.remoteaccess.certs.cakey }}
  ca.key: {{ .Values.remoteaccess.certs.cakey }}
{{- end }}
  tls.crt: {{ .Values.remoteaccess.certs.servercert }}
  tls.key: {{ .Values.remoteaccess.certs.serverkey }}
{{- end }}
