{{- if .Values.remoteaccess.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns-management.fullname" . }}-remoteaccess-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.remoteaccess.certs.ca.cert }}
{{- if not .Values.remoteaccess.certs.server.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns-management.fullname" . }}-remoteaccess-server
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  tls.crt: {{ .Values.remoteaccess.certs.server.cert }}
  tls.key: {{ .Values.remoteaccess.certs.server.key }}
{{- end }}
{{- end }}
