{{- if .Values.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1beta2"
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "external-dns-management.fullname" . }}-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "external-dns-management.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
{{- end }}
