// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSEntries implements DNSEntryInterface
type FakeDNSEntries struct {
	Fake *FakeDnsV1alpha1
	ns   string
}

var dnsentriesResource = v1alpha1.SchemeGroupVersion.WithResource("dnsentries")

var dnsentriesKind = v1alpha1.SchemeGroupVersion.WithKind("DNSEntry")

// Get takes name of the dNSEntry, and returns the corresponding dNSEntry object, and an error if there is any.
func (c *FakeDNSEntries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DNSEntry, err error) {
	emptyResult := &v1alpha1.DNSEntry{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(dnsentriesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSEntry), err
}

// List takes label and field selectors, and returns the list of DNSEntries that match those selectors.
func (c *FakeDNSEntries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DNSEntryList, err error) {
	emptyResult := &v1alpha1.DNSEntryList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(dnsentriesResource, dnsentriesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DNSEntryList{ListMeta: obj.(*v1alpha1.DNSEntryList).ListMeta}
	for _, item := range obj.(*v1alpha1.DNSEntryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSEntries.
func (c *FakeDNSEntries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(dnsentriesResource, c.ns, opts))

}

// Create takes the representation of a dNSEntry and creates it.  Returns the server's representation of the dNSEntry, and an error, if there is any.
func (c *FakeDNSEntries) Create(ctx context.Context, dNSEntry *v1alpha1.DNSEntry, opts v1.CreateOptions) (result *v1alpha1.DNSEntry, err error) {
	emptyResult := &v1alpha1.DNSEntry{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(dnsentriesResource, c.ns, dNSEntry, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSEntry), err
}

// Update takes the representation of a dNSEntry and updates it. Returns the server's representation of the dNSEntry, and an error, if there is any.
func (c *FakeDNSEntries) Update(ctx context.Context, dNSEntry *v1alpha1.DNSEntry, opts v1.UpdateOptions) (result *v1alpha1.DNSEntry, err error) {
	emptyResult := &v1alpha1.DNSEntry{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(dnsentriesResource, c.ns, dNSEntry, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSEntry), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDNSEntries) UpdateStatus(ctx context.Context, dNSEntry *v1alpha1.DNSEntry, opts v1.UpdateOptions) (result *v1alpha1.DNSEntry, err error) {
	emptyResult := &v1alpha1.DNSEntry{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(dnsentriesResource, "status", c.ns, dNSEntry, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSEntry), err
}

// Delete takes name of the dNSEntry and deletes it. Returns an error if one occurs.
func (c *FakeDNSEntries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dnsentriesResource, c.ns, name, opts), &v1alpha1.DNSEntry{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSEntries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(dnsentriesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DNSEntryList{})
	return err
}

// Patch applies the patch and returns the patched dNSEntry.
func (c *FakeDNSEntries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DNSEntry, err error) {
	emptyResult := &v1alpha1.DNSEntry{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(dnsentriesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSEntry), err
}
