// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	dnsv1alpha1 "github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDNSEntries implements DNSEntryInterface
type fakeDNSEntries struct {
	*gentype.FakeClientWithList[*v1alpha1.DNSEntry, *v1alpha1.DNSEntryList]
	Fake *FakeDnsV1alpha1
}

func newFakeDNSEntries(fake *FakeDnsV1alpha1, namespace string) dnsv1alpha1.DNSEntryInterface {
	return &fakeDNSEntries{
		gentype.NewFakeClientWithList[*v1alpha1.DNSEntry, *v1alpha1.DNSEntryList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("dnsentries"),
			v1alpha1.SchemeGroupVersion.WithKind("DNSEntry"),
			func() *v1alpha1.DNSEntry { return &v1alpha1.DNSEntry{} },
			func() *v1alpha1.DNSEntryList { return &v1alpha1.DNSEntryList{} },
			func(dst, src *v1alpha1.DNSEntryList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.DNSEntryList) []*v1alpha1.DNSEntry { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.DNSEntryList, items []*v1alpha1.DNSEntry) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
