// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSLocks implements DNSLockInterface
type FakeDNSLocks struct {
	Fake *FakeDnsV1alpha1
	ns   string
}

var dnslocksResource = v1alpha1.SchemeGroupVersion.WithResource("dnslocks")

var dnslocksKind = v1alpha1.SchemeGroupVersion.WithKind("DNSLock")

// Get takes name of the dNSLock, and returns the corresponding dNSLock object, and an error if there is any.
func (c *FakeDNSLocks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DNSLock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dnslocksResource, c.ns, name), &v1alpha1.DNSLock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNSLock), err
}

// List takes label and field selectors, and returns the list of DNSLocks that match those selectors.
func (c *FakeDNSLocks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DNSLockList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dnslocksResource, dnslocksKind, c.ns, opts), &v1alpha1.DNSLockList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DNSLockList{ListMeta: obj.(*v1alpha1.DNSLockList).ListMeta}
	for _, item := range obj.(*v1alpha1.DNSLockList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSLocks.
func (c *FakeDNSLocks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dnslocksResource, c.ns, opts))

}

// Create takes the representation of a dNSLock and creates it.  Returns the server's representation of the dNSLock, and an error, if there is any.
func (c *FakeDNSLocks) Create(ctx context.Context, dNSLock *v1alpha1.DNSLock, opts v1.CreateOptions) (result *v1alpha1.DNSLock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dnslocksResource, c.ns, dNSLock), &v1alpha1.DNSLock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNSLock), err
}

// Update takes the representation of a dNSLock and updates it. Returns the server's representation of the dNSLock, and an error, if there is any.
func (c *FakeDNSLocks) Update(ctx context.Context, dNSLock *v1alpha1.DNSLock, opts v1.UpdateOptions) (result *v1alpha1.DNSLock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dnslocksResource, c.ns, dNSLock), &v1alpha1.DNSLock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNSLock), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDNSLocks) UpdateStatus(ctx context.Context, dNSLock *v1alpha1.DNSLock, opts v1.UpdateOptions) (*v1alpha1.DNSLock, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dnslocksResource, "status", c.ns, dNSLock), &v1alpha1.DNSLock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNSLock), err
}

// Delete takes name of the dNSLock and deletes it. Returns an error if one occurs.
func (c *FakeDNSLocks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dnslocksResource, c.ns, name, opts), &v1alpha1.DNSLock{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSLocks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dnslocksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DNSLockList{})
	return err
}

// Patch applies the patch and returns the patched dNSLock.
func (c *FakeDNSLocks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DNSLock, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dnslocksResource, c.ns, name, pt, data, subresources...), &v1alpha1.DNSLock{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNSLock), err
}
