// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSHostedZonePolicies implements DNSHostedZonePolicyInterface
type FakeDNSHostedZonePolicies struct {
	Fake *FakeDnsV1alpha1
	ns   string
}

var dnshostedzonepoliciesResource = v1alpha1.SchemeGroupVersion.WithResource("dnshostedzonepolicies")

var dnshostedzonepoliciesKind = v1alpha1.SchemeGroupVersion.WithKind("DNSHostedZonePolicy")

// Get takes name of the dNSHostedZonePolicy, and returns the corresponding dNSHostedZonePolicy object, and an error if there is any.
func (c *FakeDNSHostedZonePolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DNSHostedZonePolicy, err error) {
	emptyResult := &v1alpha1.DNSHostedZonePolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(dnshostedzonepoliciesResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSHostedZonePolicy), err
}

// List takes label and field selectors, and returns the list of DNSHostedZonePolicies that match those selectors.
func (c *FakeDNSHostedZonePolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DNSHostedZonePolicyList, err error) {
	emptyResult := &v1alpha1.DNSHostedZonePolicyList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(dnshostedzonepoliciesResource, dnshostedzonepoliciesKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DNSHostedZonePolicyList{ListMeta: obj.(*v1alpha1.DNSHostedZonePolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.DNSHostedZonePolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSHostedZonePolicies.
func (c *FakeDNSHostedZonePolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(dnshostedzonepoliciesResource, c.ns, opts))

}

// Create takes the representation of a dNSHostedZonePolicy and creates it.  Returns the server's representation of the dNSHostedZonePolicy, and an error, if there is any.
func (c *FakeDNSHostedZonePolicies) Create(ctx context.Context, dNSHostedZonePolicy *v1alpha1.DNSHostedZonePolicy, opts v1.CreateOptions) (result *v1alpha1.DNSHostedZonePolicy, err error) {
	emptyResult := &v1alpha1.DNSHostedZonePolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(dnshostedzonepoliciesResource, c.ns, dNSHostedZonePolicy, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSHostedZonePolicy), err
}

// Update takes the representation of a dNSHostedZonePolicy and updates it. Returns the server's representation of the dNSHostedZonePolicy, and an error, if there is any.
func (c *FakeDNSHostedZonePolicies) Update(ctx context.Context, dNSHostedZonePolicy *v1alpha1.DNSHostedZonePolicy, opts v1.UpdateOptions) (result *v1alpha1.DNSHostedZonePolicy, err error) {
	emptyResult := &v1alpha1.DNSHostedZonePolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(dnshostedzonepoliciesResource, c.ns, dNSHostedZonePolicy, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSHostedZonePolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDNSHostedZonePolicies) UpdateStatus(ctx context.Context, dNSHostedZonePolicy *v1alpha1.DNSHostedZonePolicy, opts v1.UpdateOptions) (result *v1alpha1.DNSHostedZonePolicy, err error) {
	emptyResult := &v1alpha1.DNSHostedZonePolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(dnshostedzonepoliciesResource, "status", c.ns, dNSHostedZonePolicy, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSHostedZonePolicy), err
}

// Delete takes name of the dNSHostedZonePolicy and deletes it. Returns an error if one occurs.
func (c *FakeDNSHostedZonePolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(dnshostedzonepoliciesResource, c.ns, name, opts), &v1alpha1.DNSHostedZonePolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSHostedZonePolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(dnshostedzonepoliciesResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DNSHostedZonePolicyList{})
	return err
}

// Patch applies the patch and returns the patched dNSHostedZonePolicy.
func (c *FakeDNSHostedZonePolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DNSHostedZonePolicy, err error) {
	emptyResult := &v1alpha1.DNSHostedZonePolicy{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(dnshostedzonepoliciesResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.DNSHostedZonePolicy), err
}
