// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	dnsv1alpha1 "github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDNSProviders implements DNSProviderInterface
type fakeDNSProviders struct {
	*gentype.FakeClientWithList[*v1alpha1.DNSProvider, *v1alpha1.DNSProviderList]
	Fake *FakeDnsV1alpha1
}

func newFakeDNSProviders(fake *FakeDnsV1alpha1, namespace string) dnsv1alpha1.DNSProviderInterface {
	return &fakeDNSProviders{
		gentype.NewFakeClientWithList[*v1alpha1.DNSProvider, *v1alpha1.DNSProviderList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("dnsproviders"),
			v1alpha1.SchemeGroupVersion.WithKind("DNSProvider"),
			func() *v1alpha1.DNSProvider { return &v1alpha1.DNSProvider{} },
			func() *v1alpha1.DNSProviderList { return &v1alpha1.DNSProviderList{} },
			func(dst, src *v1alpha1.DNSProviderList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.DNSProviderList) []*v1alpha1.DNSProvider {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.DNSProviderList, items []*v1alpha1.DNSProvider) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
