// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	dnsv1alpha1 "github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDNSAnnotations implements DNSAnnotationInterface
type fakeDNSAnnotations struct {
	*gentype.FakeClientWithList[*v1alpha1.DNSAnnotation, *v1alpha1.DNSAnnotationList]
	Fake *FakeDnsV1alpha1
}

func newFakeDNSAnnotations(fake *FakeDnsV1alpha1, namespace string) dnsv1alpha1.DNSAnnotationInterface {
	return &fakeDNSAnnotations{
		gentype.NewFakeClientWithList[*v1alpha1.DNSAnnotation, *v1alpha1.DNSAnnotationList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("dnsannotations"),
			v1alpha1.SchemeGroupVersion.WithKind("DNSAnnotation"),
			func() *v1alpha1.DNSAnnotation { return &v1alpha1.DNSAnnotation{} },
			func() *v1alpha1.DNSAnnotationList { return &v1alpha1.DNSAnnotationList{} },
			func(dst, src *v1alpha1.DNSAnnotationList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.DNSAnnotationList) []*v1alpha1.DNSAnnotation {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.DNSAnnotationList, items []*v1alpha1.DNSAnnotation) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
