// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDnsV1alpha1 struct {
	*testing.Fake
}

func (c *FakeDnsV1alpha1) DNSAnnotations(namespace string) v1alpha1.DNSAnnotationInterface {
	return &FakeDNSAnnotations{c, namespace}
}

func (c *FakeDnsV1alpha1) DNSEntries(namespace string) v1alpha1.DNSEntryInterface {
	return &FakeDNSEntries{c, namespace}
}

func (c *FakeDnsV1alpha1) DNSHostedZonePolicies(namespace string) v1alpha1.DNSHostedZonePolicyInterface {
	return &FakeDNSHostedZonePolicies{c, namespace}
}

func (c *FakeDnsV1alpha1) DNSOwners(namespace string) v1alpha1.DNSOwnerInterface {
	return &FakeDNSOwners{c, namespace}
}

func (c *FakeDnsV1alpha1) DNSProviders(namespace string) v1alpha1.DNSProviderInterface {
	return &FakeDNSProviders{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDnsV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
