// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	dnsv1alpha1 "github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/typed/dns/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeDNSOwners implements DNSOwnerInterface
type fakeDNSOwners struct {
	*gentype.FakeClientWithList[*v1alpha1.DNSOwner, *v1alpha1.DNSOwnerList]
	Fake *FakeDnsV1alpha1
}

func newFakeDNSOwners(fake *FakeDnsV1alpha1, namespace string) dnsv1alpha1.DNSOwnerInterface {
	return &fakeDNSOwners{
		gentype.NewFakeClientWithList[*v1alpha1.DNSOwner, *v1alpha1.DNSOwnerList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("dnsowners"),
			v1alpha1.SchemeGroupVersion.WithKind("DNSOwner"),
			func() *v1alpha1.DNSOwner { return &v1alpha1.DNSOwner{} },
			func() *v1alpha1.DNSOwnerList { return &v1alpha1.DNSOwnerList{} },
			func(dst, src *v1alpha1.DNSOwnerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.DNSOwnerList) []*v1alpha1.DNSOwner { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.DNSOwnerList, items []*v1alpha1.DNSOwner) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
