/*
Copyright (c) 2022 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRemoteAccessCertificates implements RemoteAccessCertificateInterface
type FakeRemoteAccessCertificates struct {
	Fake *FakeDnsV1alpha1
	ns   string
}

var remoteaccesscertificatesResource = schema.GroupVersionResource{Group: "dns.gardener.cloud", Version: "v1alpha1", Resource: "remoteaccesscertificates"}

var remoteaccesscertificatesKind = schema.GroupVersionKind{Group: "dns.gardener.cloud", Version: "v1alpha1", Kind: "RemoteAccessCertificate"}

// Get takes name of the remoteAccessCertificate, and returns the corresponding remoteAccessCertificate object, and an error if there is any.
func (c *FakeRemoteAccessCertificates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RemoteAccessCertificate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(remoteaccesscertificatesResource, c.ns, name), &v1alpha1.RemoteAccessCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RemoteAccessCertificate), err
}

// List takes label and field selectors, and returns the list of RemoteAccessCertificates that match those selectors.
func (c *FakeRemoteAccessCertificates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RemoteAccessCertificateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(remoteaccesscertificatesResource, remoteaccesscertificatesKind, c.ns, opts), &v1alpha1.RemoteAccessCertificateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RemoteAccessCertificateList{ListMeta: obj.(*v1alpha1.RemoteAccessCertificateList).ListMeta}
	for _, item := range obj.(*v1alpha1.RemoteAccessCertificateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested remoteAccessCertificates.
func (c *FakeRemoteAccessCertificates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(remoteaccesscertificatesResource, c.ns, opts))

}

// Create takes the representation of a remoteAccessCertificate and creates it.  Returns the server's representation of the remoteAccessCertificate, and an error, if there is any.
func (c *FakeRemoteAccessCertificates) Create(ctx context.Context, remoteAccessCertificate *v1alpha1.RemoteAccessCertificate, opts v1.CreateOptions) (result *v1alpha1.RemoteAccessCertificate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(remoteaccesscertificatesResource, c.ns, remoteAccessCertificate), &v1alpha1.RemoteAccessCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RemoteAccessCertificate), err
}

// Update takes the representation of a remoteAccessCertificate and updates it. Returns the server's representation of the remoteAccessCertificate, and an error, if there is any.
func (c *FakeRemoteAccessCertificates) Update(ctx context.Context, remoteAccessCertificate *v1alpha1.RemoteAccessCertificate, opts v1.UpdateOptions) (result *v1alpha1.RemoteAccessCertificate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(remoteaccesscertificatesResource, c.ns, remoteAccessCertificate), &v1alpha1.RemoteAccessCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RemoteAccessCertificate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRemoteAccessCertificates) UpdateStatus(ctx context.Context, remoteAccessCertificate *v1alpha1.RemoteAccessCertificate, opts v1.UpdateOptions) (*v1alpha1.RemoteAccessCertificate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(remoteaccesscertificatesResource, "status", c.ns, remoteAccessCertificate), &v1alpha1.RemoteAccessCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RemoteAccessCertificate), err
}

// Delete takes name of the remoteAccessCertificate and deletes it. Returns an error if one occurs.
func (c *FakeRemoteAccessCertificates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(remoteaccesscertificatesResource, c.ns, name, opts), &v1alpha1.RemoteAccessCertificate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRemoteAccessCertificates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(remoteaccesscertificatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RemoteAccessCertificateList{})
	return err
}

// Patch applies the patch and returns the patched remoteAccessCertificate.
func (c *FakeRemoteAccessCertificates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RemoteAccessCertificate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(remoteaccesscertificatesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RemoteAccessCertificate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RemoteAccessCertificate), err
}
