version: "2"
run:
  concurrency: 4
linters:
  enable:
    - copyloopvar
    - ginkgolinter
    - importas
    - nilerr
    - revive
    - whitespace
  settings:
    loggercheck:
      require-string-key: true
      no-printf-like: true
    revive:
      rules:
        - name: duplicated-imports
        - name: unused-parameter
        - name: unreachable-code
        - name: context-as-argument
        - name: early-return
        - name: exported
  exclusions:
    generated: lax
    rules:
      - linters:
          - staticcheck
        text: 'ST1001:' # should not use dot imports
      - linters:
          - staticcheck
        text: 'ST1006:' # receiver name should be a reflection of its identity; don't use generic names such as "this" or "self"
      - path: (.+)\.go$
        text: Error return value of `testEnv.*` is not checked
      - path: pkg/controller/provider/remote/handler\.go$
        text: 'Will be supported throughout 1.x.' # use grpc.WithAuthority instead
      - path: pkg/server/remote/embed/dynamictransportcreds\.go$
        text: 'Will be supported throughout 1.x.' # use grpc.WithAuthority instead
      - path: pkg/dns/provider/lookupprocessor\.go$
        text: 'netErr.Temporary has been deprecated since Go 1.18'
      - path: pkg/(apis|controller|dns|server)/(.+)\.go$
        text: 'exported: '
      - path: test/(.+)\.go$
        text: 'exported: '
      - path: pkg/dnsman2/(.+)\.go$
        text: ' by other packages, and that stutters'
    paths:
      - zz_generated.*\.go$
      - test/functional/config
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
