// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	dnsv1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	scheme "github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type DnsV1alpha1Interface interface {
	RESTClient() rest.Interface
	DNSAnnotationsGetter
	DNSEntriesGetter
	DNSHostedZonePoliciesGetter
	DNSProvidersGetter
}

// DnsV1alpha1Client is used to interact with features provided by the dns.gardener.cloud group.
type DnsV1alpha1Client struct {
	restClient rest.Interface
}

func (c *DnsV1alpha1Client) DNSAnnotations(namespace string) DNSAnnotationInterface {
	return newDNSAnnotations(c, namespace)
}

func (c *DnsV1alpha1Client) DNSEntries(namespace string) DNSEntryInterface {
	return newDNSEntries(c, namespace)
}

func (c *DnsV1alpha1Client) DNSHostedZonePolicies(namespace string) DNSHostedZonePolicyInterface {
	return newDNSHostedZonePolicies(c, namespace)
}

func (c *DnsV1alpha1Client) DNSProviders(namespace string) DNSProviderInterface {
	return newDNSProviders(c, namespace)
}

// NewForConfig creates a new DnsV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*DnsV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new DnsV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*DnsV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &DnsV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new DnsV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *DnsV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new DnsV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *DnsV1alpha1Client {
	return &DnsV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := dnsv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *DnsV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
