// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1alpha1 "github.com/gardener/external-dns-management/pkg/apis/dns/v1alpha1"
	scheme "github.com/gardener/external-dns-management/pkg/client/dns/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// DNSHostedZonePoliciesGetter has a method to return a DNSHostedZonePolicyInterface.
// A group's client should implement this interface.
type DNSHostedZonePoliciesGetter interface {
	DNSHostedZonePolicies(namespace string) DNSHostedZonePolicyInterface
}

// DNSHostedZonePolicyInterface has methods to work with DNSHostedZonePolicy resources.
type DNSHostedZonePolicyInterface interface {
	Create(ctx context.Context, dNSHostedZonePolicy *v1alpha1.DNSHostedZonePolicy, opts v1.CreateOptions) (*v1alpha1.DNSHostedZonePolicy, error)
	Update(ctx context.Context, dNSHostedZonePolicy *v1alpha1.DNSHostedZonePolicy, opts v1.UpdateOptions) (*v1alpha1.DNSHostedZonePolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, dNSHostedZonePolicy *v1alpha1.DNSHostedZonePolicy, opts v1.UpdateOptions) (*v1alpha1.DNSHostedZonePolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DNSHostedZonePolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DNSHostedZonePolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DNSHostedZonePolicy, err error)
	DNSHostedZonePolicyExpansion
}

// dNSHostedZonePolicies implements DNSHostedZonePolicyInterface
type dNSHostedZonePolicies struct {
	*gentype.ClientWithList[*v1alpha1.DNSHostedZonePolicy, *v1alpha1.DNSHostedZonePolicyList]
}

// newDNSHostedZonePolicies returns a DNSHostedZonePolicies
func newDNSHostedZonePolicies(c *DnsV1alpha1Client, namespace string) *dNSHostedZonePolicies {
	return &dNSHostedZonePolicies{
		gentype.NewClientWithList[*v1alpha1.DNSHostedZonePolicy, *v1alpha1.DNSHostedZonePolicyList](
			"dnshostedzonepolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.DNSHostedZonePolicy { return &v1alpha1.DNSHostedZonePolicy{} },
			func() *v1alpha1.DNSHostedZonePolicyList { return &v1alpha1.DNSHostedZonePolicyList{} }),
	}
}
