// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type DNSAnnotationExpansion interface{}

type DNSEntryExpansion interface{}

type DNSHostedZonePolicyExpansion interface{}

type DNSProviderExpansion interface{}
