apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- name: cluster
  targetType: landscaper.gardener.cloud/kubernetes-cluster

- name: chartValues
  required: false
  schema:
    type: object

deployExecutions:
- file: /deploy-executions.yaml
  name: manifests
  type: GoTemplate

