#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

set -e

cd "$(dirname "$0")/.."
make check

echo "running code generator..."
make generate