#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: Copyright Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

set -e

echo "Running integration tests..."
cd "$(dirname "$0")/.."
make integrationtests
