#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: Copyright Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

set -e

repo_root="$(git rev-parse --show-toplevel)"


version_file="$(readlink -f "${repo_root}/VERSION")"
version="$(cat "${version_file}")"
versiontag="${version//-dev/-master}"

sed -i -e "s/  tag: .*/  tag: ${versiontag}/" "${repo_root}/charts/external-dns-management/values.yaml"
