#!/usr/bin/env bash
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e


# add full-fleshed tar
apk update
apk add --no-cache tar


if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

"${SOURCE_PATH}/hack/generate-controller-registration.sh" \
  dns-external \
  "${SOURCE_PATH}/charts/external-dns-management/" \
  "${SOURCE_PATH}/examples/controller-registration.yaml" \
  DNSProvider:aws-route53 DNSProvider:alicloud-dns DNSProvider:azure-dns DNSProvider:google-clouddns DNSProvider:openstack-designate DNSProvider:cloudflare-dns

VERSION_FILE="$(readlink -f "${SOURCE_PATH}/VERSION")"
VERSION="$(cat "${VERSION_FILE}")"
VERSIONTAG="${VERSION//-dev/-master}"

sed -i -e "s/  tag: .*/  tag: ${VERSIONTAG}/" "${SOURCE_PATH}/charts/external-dns-management/values.yaml"
