#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e


# add full-fleshed tar and helm
BASE_URL="https://get.helm.sh"
HELM_VERSION=v3.13.1
TAR_FILE="helm-${HELM_VERSION}-linux-amd64.tar.gz"

apk add --update --no-cache curl ca-certificates tar 
curl -L ${BASE_URL}/${TAR_FILE} |tar xvz 
mv linux-amd64/helm /usr/bin/helm 
chmod +x /usr/bin/helm 
export HELM=/usr/bin/helm

if [[ -z "${SOURCE_PATH}" ]]; then
  export SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"
else
  export SOURCE_PATH="$(readlink -f "${SOURCE_PATH}")"
fi

VERSION_FILE="$(readlink -f "${SOURCE_PATH}/VERSION")"
VERSION="$(cat "${VERSION_FILE}")"
VERSIONTAG="${VERSION//-dev/-master}"

sed -i -e "s/  tag: .*/  tag: ${VERSIONTAG}/" "${SOURCE_PATH}/charts/external-dns-management/values.yaml"
