#!/bin/bash
#
# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

rm -f ${GOPATH}/bin/*-gen

CURRENT_DIR=$(dirname $0)
PROJECT_ROOT="${CURRENT_DIR}"/..

source "$PROJECT_ROOT/build/settings.src"

# Go modules are not able to properly vendor k8s.io/code-generator@kubernetes-1.14.0 (build with godep)
# to include also generate-groups.sh and generate-internal-groups.sh scripts under vendor/.
# However this is fixed with kubernetes-1.15.0 (k8s.io/code-generator@kubernetes-1.15.0 is opted in go modules).
# The workaround for now is to have a kubernetes-1.14.0 copy of the 2 scripts under hack/code-generator and
# to copy them to vendor/vendor/k8s.io/code-generator/ for the generation.
# And respectively clean up them after execution.
# The workaround should be removed adopting kubernetes-1.15.0.
# Similar thing is also done in https://github.com/heptio/contour/pull/1010.

cp "${CURRENT_DIR}"/code-generator/generate-*.sh "${PROJECT_ROOT}"/vendor/k8s.io/code-generator/

cleanup() {
  rm -f "${PROJECT_ROOT}"/vendor/k8s.io/code-generator/generate-groups.sh
}
trap "cleanup" EXIT SIGINT

rm -rf "$SCRIPT_ROOT/pkg/client/$APINAME"

bash "${PROJECT_ROOT}"/vendor/k8s.io/code-generator/generate-groups.sh \
  "deepcopy,client,informer,lister" \
  $PKGPATH/pkg/client/$APINAME \
  $PKGPATH/pkg/apis \
  $APINAME:$APIVERSION \
  -h "${PROJECT_ROOT}/hack/LICENSE_BOILERPLATE.txt"
