#!/bin/bash
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

SOURCE_PATH="$(readlink -f "$(dirname ${0})/..")"

# setup virtual GOPATH
source "$CONTROLLER_MANAGER_LIB_HACK_DIR"/vgopath-setup.sh

CODE_GEN_DIR=$(go list -m -f '{{.Dir}}' k8s.io/code-generator)

rm -f ${GOPATH}/bin/*-gen

# We need to explicitly pass GO111MODULE=off to k8s.io/code-generator as it is significantly slower otherwise,
# see https://github.com/kubernetes/code-generator/issues/100.
export GO111MODULE=off

rm -rf "${SOURCE_PATH}/pkg/client/dns"
PROJECT_ROOT=$(dirname $0)/..


bash "${CODE_GEN_DIR}"/generate-internal-groups.sh \
  "deepcopy,client,informer,lister" \
  github.com/gardener/external-dns-management/pkg/client/dns \
  "" \
  github.com/gardener/external-dns-management/pkg/apis \
  "dns:v1alpha1" \
  --go-header-file "${SOURCE_PATH}/hack/LICENSE_BOILERPLATE.txt"
