apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: default
type: Opaque
data:
  # replace '...' with values encoded as base64
  # The token should have permission of Zone:Read and DNS:Edit for all zones.
  # You can optionally exclude certain zones
  # see https://support.cloudflare.com/hc/en-us/articles/200167836-Managing-API-Tokens-and-Keys
  # For details see https://github.com/gardener/external-dns-management/blob/master/docs/cloudflare/README.md#using-the-api-token
  CLOUDFLARE_API_TOKEN: ...
    # Alternatively use Gardener cloud provider credentials convention
  #apiToken: ...
