apiVersion: v1
kind: Secret
metadata:
  name: gdc-credentials
  namespace: default
type: Opaque
data:
  # replace '...' with base64 encoded service account JSON file
  serviceaccount.json: ...
  # replace '...' with base64 encoded org cluster config JSON (orgClusterURL and caData)
  gdch-config: ...
