apiVersion: v1
kind: Secret
metadata:
  name: rfc2136-credentials
  namespace: default
type: Opaque
data:
  # Replace '...' with values encoded as base64.
  Server: ... # "<host>[:<port>]" of the authorive DNS server, default port is 53
  TSIGKeyName: ... # key name of the TSIG secret (must end with a dot)
  TSIGSecret: ... # TSIG secret
  Zone: ... # zone (must be fully qualified)
  # the algorithm is optional. By default 'hmac-sha256' is assumed.
  #TSIGSecretAlgorithm: ... # TSIG Algorithm Name for Hash-based Message Authentication (HMAC).
