apiVersion: v1
kind: Secret
metadata:
  name: remote-credentials
  namespace: default
type: Opaque
data:
  # Replace '...' with values encoded as base64.
  REMOTE_ENDPOINT: ...  # "<host>:<port>" of the remote-access service running on the remotely dns-controller-manager
  NAMESPACE: ... # <namespace> of the remote cluster. All included zones of all namespace's DNSProvider objects annotated with 'dns.gardener.cloud/remote-access=true' are available.
  tls.crt: ... # client certificate
  tls.key: ... # client private key
  ca.crt: ... # optional CA used for the server certificate
  #OVERRIDE_SERVER_NAME: ... # optional override server name as specified in the server certificate
