apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
  namespace: default
type: Opaque
data:
  # replace '...' with the API Key generated. The token should have permission of Zone:Read and DNS:Edit for all zones.
  # You can optionally exclude certain zones
  # see https://support.cloudflare.com/hc/en-us/articles/200167836-Managing-API-Tokens-and-Keys
  # For details see https://github.com/SayakMukhopadhyay/external-dns-management/blob/master/doc/cloudflare/README.md#using-the-api-key
  CLOUDFLARE_API_TOKEN: ...
