apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: azure
  namespace: default
spec:
  type: azure-dns
  secretRef:
    name: azure-credentials
  domains:
    include:
    - my.own.domain.com
    #exclude:
    #- my.excluded.domain.com
  #zones:
  #  include:
  #  - myResourceGroup/own.domain.com
  #  - <resourceGroup>/<dnszone>
  #  exclude:
  #  - <resourceGroup>/<dnszone>
