apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: aws
  namespace: default
spec:
  type: aws-route53
  secretRef:
    name: aws-credentials
  domains:
    include:
    - my.own.domain.com
    #exclude:
    #- my.excluded.domain.com
  #zones:
  #  include:
  #  - <ZONEID>
  #  exclude:
  #  - <ZONEID>
  #defaultTTL: 300
  #rateLimit:
  #  requestsPerDay: 240
  #  burst: 20