apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: openstack
  namespace: default
spec:
  type: openstack-designate
  secretRef:
    name: openstack-credentials
  domains:
    include:
    - my.own.domain.com
