apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSEntry
metadata:
  annotations:
    # If you are delegating the DNS management to Gardener, uncomment the following line (see https://gardener.cloud/documentation/guides/administer_shoots/dns_names/)
    #dns.gardener.cloud/class: garden
    # To temporarily skip reconciliation of an entry
    #dns.gardener.cloud/ignore: "reconcile" # or "true"
    # To skip reconciliation and cleanup of DNS records on deletion of an entry
    #dns.gardener.cloud/ignore: "full"
  name: dns
  namespace: default
spec:
  dnsName: "dns.ringtest.dev.k8s.ondemand.com"
  ttl: 600
  targets:
  - 8.8.8.8
