apiVersion: v1
kind: Service
metadata:
  annotations:
    dns.gardener.cloud/dnsnames: echo.ringtest.dev.k8s.ondemand.com
    dns.gardener.cloud/ttl: "500"
  name: test-service
  namespace: default
spec:
  ports:
  - name: http
    nodePort: 31787
    port: 80
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: LoadBalancer
