apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: google
  namespace: default
spec:
  type: google-clouddns
  secretRef:
    name: google-credentials
  domains:
    include:
    - my.own.domain.com
