apiVersion: dns.gardener.cloud/v1alpha1
kind: DNSProvider
metadata:
  name: openstack
  namespace: default
spec:
  type: Designate
  secretRef:
    name: openstack-credentials
  domains:
    include:
      - ringtest.dev.k8s.ondemand.com