//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Contributors to the Gardener project
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	config "github.com/gardener/external-dns-management/pkg/dnsman2/apis/config"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	componentbaseconfig "k8s.io/component-base/config"
	configv1alpha1 "k8s.io/component-base/config/v1alpha1"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*AdvancedOptions)(nil), (*config.AdvancedOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AdvancedOptions_To_config_AdvancedOptions(a.(*AdvancedOptions), b.(*config.AdvancedOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.AdvancedOptions)(nil), (*AdvancedOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_AdvancedOptions_To_v1alpha1_AdvancedOptions(a.(*config.AdvancedOptions), b.(*AdvancedOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClientConnection)(nil), (*config.ClientConnection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClientConnection_To_config_ClientConnection(a.(*ClientConnection), b.(*config.ClientConnection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ClientConnection)(nil), (*ClientConnection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ClientConnection_To_v1alpha1_ClientConnection(a.(*config.ClientConnection), b.(*ClientConnection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneClientConnection)(nil), (*config.ControlPlaneClientConnection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneClientConnection_To_config_ControlPlaneClientConnection(a.(*ControlPlaneClientConnection), b.(*config.ControlPlaneClientConnection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControlPlaneClientConnection)(nil), (*ControlPlaneClientConnection)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControlPlaneClientConnection_To_v1alpha1_ControlPlaneClientConnection(a.(*config.ControlPlaneClientConnection), b.(*ControlPlaneClientConnection), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControllerConfiguration)(nil), (*config.ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(a.(*ControllerConfiguration), b.(*config.ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ControllerConfiguration)(nil), (*ControllerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(a.(*config.ControllerConfiguration), b.(*ControllerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DNSAnnotationControllerConfig)(nil), (*config.DNSAnnotationControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DNSAnnotationControllerConfig_To_config_DNSAnnotationControllerConfig(a.(*DNSAnnotationControllerConfig), b.(*config.DNSAnnotationControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DNSAnnotationControllerConfig)(nil), (*DNSAnnotationControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DNSAnnotationControllerConfig_To_v1alpha1_DNSAnnotationControllerConfig(a.(*config.DNSAnnotationControllerConfig), b.(*DNSAnnotationControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DNSEntryControllerConfig)(nil), (*config.DNSEntryControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DNSEntryControllerConfig_To_config_DNSEntryControllerConfig(a.(*DNSEntryControllerConfig), b.(*config.DNSEntryControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DNSEntryControllerConfig)(nil), (*DNSEntryControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DNSEntryControllerConfig_To_v1alpha1_DNSEntryControllerConfig(a.(*config.DNSEntryControllerConfig), b.(*DNSEntryControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DNSManagerConfiguration)(nil), (*config.DNSManagerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DNSManagerConfiguration_To_config_DNSManagerConfiguration(a.(*DNSManagerConfiguration), b.(*config.DNSManagerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DNSManagerConfiguration)(nil), (*DNSManagerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DNSManagerConfiguration_To_v1alpha1_DNSManagerConfiguration(a.(*config.DNSManagerConfiguration), b.(*DNSManagerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DNSProviderControllerConfig)(nil), (*config.DNSProviderControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DNSProviderControllerConfig_To_config_DNSProviderControllerConfig(a.(*DNSProviderControllerConfig), b.(*config.DNSProviderControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.DNSProviderControllerConfig)(nil), (*DNSProviderControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_DNSProviderControllerConfig_To_v1alpha1_DNSProviderControllerConfig(a.(*config.DNSProviderControllerConfig), b.(*DNSProviderControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPWorkloadIdentityConfig)(nil), (*config.GCPWorkloadIdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GCPWorkloadIdentityConfig_To_config_GCPWorkloadIdentityConfig(a.(*GCPWorkloadIdentityConfig), b.(*config.GCPWorkloadIdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.GCPWorkloadIdentityConfig)(nil), (*GCPWorkloadIdentityConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_GCPWorkloadIdentityConfig_To_v1alpha1_GCPWorkloadIdentityConfig(a.(*config.GCPWorkloadIdentityConfig), b.(*GCPWorkloadIdentityConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RateLimiterOptions)(nil), (*config.RateLimiterOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RateLimiterOptions_To_config_RateLimiterOptions(a.(*RateLimiterOptions), b.(*config.RateLimiterOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.RateLimiterOptions)(nil), (*RateLimiterOptions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_RateLimiterOptions_To_v1alpha1_RateLimiterOptions(a.(*config.RateLimiterOptions), b.(*RateLimiterOptions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Server)(nil), (*config.Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Server_To_config_Server(a.(*Server), b.(*config.Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.Server)(nil), (*Server)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_Server_To_v1alpha1_Server(a.(*config.Server), b.(*Server), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServerConfiguration)(nil), (*config.ServerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(a.(*ServerConfiguration), b.(*config.ServerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.ServerConfiguration)(nil), (*ServerConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(a.(*config.ServerConfiguration), b.(*ServerConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SourceControllerConfig)(nil), (*config.SourceControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SourceControllerConfig_To_config_SourceControllerConfig(a.(*SourceControllerConfig), b.(*config.SourceControllerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SourceControllerConfig)(nil), (*SourceControllerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SourceControllerConfig_To_v1alpha1_SourceControllerConfig(a.(*config.SourceControllerConfig), b.(*SourceControllerConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AdvancedOptions_To_config_AdvancedOptions(in *AdvancedOptions, out *config.AdvancedOptions, s conversion.Scope) error {
	*out = *(*config.AdvancedOptions)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_AdvancedOptions_To_config_AdvancedOptions is an autogenerated conversion function.
func Convert_v1alpha1_AdvancedOptions_To_config_AdvancedOptions(in *AdvancedOptions, out *config.AdvancedOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_AdvancedOptions_To_config_AdvancedOptions(in, out, s)
}

func autoConvert_config_AdvancedOptions_To_v1alpha1_AdvancedOptions(in *config.AdvancedOptions, out *AdvancedOptions, s conversion.Scope) error {
	*out = *(*AdvancedOptions)(unsafe.Pointer(in))
	return nil
}

// Convert_config_AdvancedOptions_To_v1alpha1_AdvancedOptions is an autogenerated conversion function.
func Convert_config_AdvancedOptions_To_v1alpha1_AdvancedOptions(in *config.AdvancedOptions, out *AdvancedOptions, s conversion.Scope) error {
	return autoConvert_config_AdvancedOptions_To_v1alpha1_AdvancedOptions(in, out, s)
}

func autoConvert_v1alpha1_ClientConnection_To_config_ClientConnection(in *ClientConnection, out *config.ClientConnection, s conversion.Scope) error {
	*out = *(*config.ClientConnection)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ClientConnection_To_config_ClientConnection is an autogenerated conversion function.
func Convert_v1alpha1_ClientConnection_To_config_ClientConnection(in *ClientConnection, out *config.ClientConnection, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClientConnection_To_config_ClientConnection(in, out, s)
}

func autoConvert_config_ClientConnection_To_v1alpha1_ClientConnection(in *config.ClientConnection, out *ClientConnection, s conversion.Scope) error {
	*out = *(*ClientConnection)(unsafe.Pointer(in))
	return nil
}

// Convert_config_ClientConnection_To_v1alpha1_ClientConnection is an autogenerated conversion function.
func Convert_config_ClientConnection_To_v1alpha1_ClientConnection(in *config.ClientConnection, out *ClientConnection, s conversion.Scope) error {
	return autoConvert_config_ClientConnection_To_v1alpha1_ClientConnection(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneClientConnection_To_config_ControlPlaneClientConnection(in *ControlPlaneClientConnection, out *config.ControlPlaneClientConnection, s conversion.Scope) error {
	*out = *(*config.ControlPlaneClientConnection)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ControlPlaneClientConnection_To_config_ControlPlaneClientConnection is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneClientConnection_To_config_ControlPlaneClientConnection(in *ControlPlaneClientConnection, out *config.ControlPlaneClientConnection, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneClientConnection_To_config_ControlPlaneClientConnection(in, out, s)
}

func autoConvert_config_ControlPlaneClientConnection_To_v1alpha1_ControlPlaneClientConnection(in *config.ControlPlaneClientConnection, out *ControlPlaneClientConnection, s conversion.Scope) error {
	*out = *(*ControlPlaneClientConnection)(unsafe.Pointer(in))
	return nil
}

// Convert_config_ControlPlaneClientConnection_To_v1alpha1_ControlPlaneClientConnection is an autogenerated conversion function.
func Convert_config_ControlPlaneClientConnection_To_v1alpha1_ControlPlaneClientConnection(in *config.ControlPlaneClientConnection, out *ControlPlaneClientConnection, s conversion.Scope) error {
	return autoConvert_config_ControlPlaneClientConnection_To_v1alpha1_ControlPlaneClientConnection(in, out, s)
}

func autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	*out = *(*config.ControllerConfiguration)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in *ControllerConfiguration, out *config.ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(in, out, s)
}

func autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	*out = *(*ControllerConfiguration)(unsafe.Pointer(in))
	return nil
}

// Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration is an autogenerated conversion function.
func Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in *config.ControllerConfiguration, out *ControllerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_DNSAnnotationControllerConfig_To_config_DNSAnnotationControllerConfig(in *DNSAnnotationControllerConfig, out *config.DNSAnnotationControllerConfig, s conversion.Scope) error {
	*out = *(*config.DNSAnnotationControllerConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_DNSAnnotationControllerConfig_To_config_DNSAnnotationControllerConfig is an autogenerated conversion function.
func Convert_v1alpha1_DNSAnnotationControllerConfig_To_config_DNSAnnotationControllerConfig(in *DNSAnnotationControllerConfig, out *config.DNSAnnotationControllerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DNSAnnotationControllerConfig_To_config_DNSAnnotationControllerConfig(in, out, s)
}

func autoConvert_config_DNSAnnotationControllerConfig_To_v1alpha1_DNSAnnotationControllerConfig(in *config.DNSAnnotationControllerConfig, out *DNSAnnotationControllerConfig, s conversion.Scope) error {
	*out = *(*DNSAnnotationControllerConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_config_DNSAnnotationControllerConfig_To_v1alpha1_DNSAnnotationControllerConfig is an autogenerated conversion function.
func Convert_config_DNSAnnotationControllerConfig_To_v1alpha1_DNSAnnotationControllerConfig(in *config.DNSAnnotationControllerConfig, out *DNSAnnotationControllerConfig, s conversion.Scope) error {
	return autoConvert_config_DNSAnnotationControllerConfig_To_v1alpha1_DNSAnnotationControllerConfig(in, out, s)
}

func autoConvert_v1alpha1_DNSEntryControllerConfig_To_config_DNSEntryControllerConfig(in *DNSEntryControllerConfig, out *config.DNSEntryControllerConfig, s conversion.Scope) error {
	*out = *(*config.DNSEntryControllerConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_DNSEntryControllerConfig_To_config_DNSEntryControllerConfig is an autogenerated conversion function.
func Convert_v1alpha1_DNSEntryControllerConfig_To_config_DNSEntryControllerConfig(in *DNSEntryControllerConfig, out *config.DNSEntryControllerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DNSEntryControllerConfig_To_config_DNSEntryControllerConfig(in, out, s)
}

func autoConvert_config_DNSEntryControllerConfig_To_v1alpha1_DNSEntryControllerConfig(in *config.DNSEntryControllerConfig, out *DNSEntryControllerConfig, s conversion.Scope) error {
	*out = *(*DNSEntryControllerConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_config_DNSEntryControllerConfig_To_v1alpha1_DNSEntryControllerConfig is an autogenerated conversion function.
func Convert_config_DNSEntryControllerConfig_To_v1alpha1_DNSEntryControllerConfig(in *config.DNSEntryControllerConfig, out *DNSEntryControllerConfig, s conversion.Scope) error {
	return autoConvert_config_DNSEntryControllerConfig_To_v1alpha1_DNSEntryControllerConfig(in, out, s)
}

func autoConvert_v1alpha1_DNSManagerConfiguration_To_config_DNSManagerConfiguration(in *DNSManagerConfiguration, out *config.DNSManagerConfiguration, s conversion.Scope) error {
	out.ClientConnection = (*config.ClientConnection)(unsafe.Pointer(in.ClientConnection))
	out.ControlPlaneClientConnection = (*config.ControlPlaneClientConnection)(unsafe.Pointer(in.ControlPlaneClientConnection))
	if err := configv1alpha1.Convert_v1alpha1_LeaderElectionConfiguration_To_config_LeaderElectionConfiguration(&in.LeaderElection, &out.LeaderElection, s); err != nil {
		return err
	}
	out.LogLevel = in.LogLevel
	out.LogFormat = in.LogFormat
	if err := Convert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(&in.Server, &out.Server, s); err != nil {
		return err
	}
	if in.Debugging != nil {
		in, out := &in.Debugging, &out.Debugging
		*out = new(componentbaseconfig.DebuggingConfiguration)
		if err := configv1alpha1.Convert_v1alpha1_DebuggingConfiguration_To_config_DebuggingConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Debugging = nil
	}
	if err := Convert_v1alpha1_ControllerConfiguration_To_config_ControllerConfiguration(&in.Controllers, &out.Controllers, s); err != nil {
		return err
	}
	out.Class = in.Class
	out.SecondaryClasses = *(*[]string)(unsafe.Pointer(&in.SecondaryClasses))
	out.DeployCRDs = (*bool)(unsafe.Pointer(in.DeployCRDs))
	out.ConditionalDeployCRDs = (*bool)(unsafe.Pointer(in.ConditionalDeployCRDs))
	out.AddShootNoCleanupLabelToCRDs = (*bool)(unsafe.Pointer(in.AddShootNoCleanupLabelToCRDs))
	out.ProviderAdvancedOptions = *(*map[string]config.AdvancedOptions)(unsafe.Pointer(&in.ProviderAdvancedOptions))
	return nil
}

// Convert_v1alpha1_DNSManagerConfiguration_To_config_DNSManagerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_DNSManagerConfiguration_To_config_DNSManagerConfiguration(in *DNSManagerConfiguration, out *config.DNSManagerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_DNSManagerConfiguration_To_config_DNSManagerConfiguration(in, out, s)
}

func autoConvert_config_DNSManagerConfiguration_To_v1alpha1_DNSManagerConfiguration(in *config.DNSManagerConfiguration, out *DNSManagerConfiguration, s conversion.Scope) error {
	out.ClientConnection = (*ClientConnection)(unsafe.Pointer(in.ClientConnection))
	out.ControlPlaneClientConnection = (*ControlPlaneClientConnection)(unsafe.Pointer(in.ControlPlaneClientConnection))
	if err := configv1alpha1.Convert_config_LeaderElectionConfiguration_To_v1alpha1_LeaderElectionConfiguration(&in.LeaderElection, &out.LeaderElection, s); err != nil {
		return err
	}
	out.LogLevel = in.LogLevel
	out.LogFormat = in.LogFormat
	if err := Convert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(&in.Server, &out.Server, s); err != nil {
		return err
	}
	if in.Debugging != nil {
		in, out := &in.Debugging, &out.Debugging
		*out = new(configv1alpha1.DebuggingConfiguration)
		if err := configv1alpha1.Convert_config_DebuggingConfiguration_To_v1alpha1_DebuggingConfiguration(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Debugging = nil
	}
	if err := Convert_config_ControllerConfiguration_To_v1alpha1_ControllerConfiguration(&in.Controllers, &out.Controllers, s); err != nil {
		return err
	}
	out.Class = in.Class
	out.SecondaryClasses = *(*[]string)(unsafe.Pointer(&in.SecondaryClasses))
	out.DeployCRDs = (*bool)(unsafe.Pointer(in.DeployCRDs))
	out.ConditionalDeployCRDs = (*bool)(unsafe.Pointer(in.ConditionalDeployCRDs))
	out.AddShootNoCleanupLabelToCRDs = (*bool)(unsafe.Pointer(in.AddShootNoCleanupLabelToCRDs))
	out.ProviderAdvancedOptions = *(*map[string]AdvancedOptions)(unsafe.Pointer(&in.ProviderAdvancedOptions))
	return nil
}

// Convert_config_DNSManagerConfiguration_To_v1alpha1_DNSManagerConfiguration is an autogenerated conversion function.
func Convert_config_DNSManagerConfiguration_To_v1alpha1_DNSManagerConfiguration(in *config.DNSManagerConfiguration, out *DNSManagerConfiguration, s conversion.Scope) error {
	return autoConvert_config_DNSManagerConfiguration_To_v1alpha1_DNSManagerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_DNSProviderControllerConfig_To_config_DNSProviderControllerConfig(in *DNSProviderControllerConfig, out *config.DNSProviderControllerConfig, s conversion.Scope) error {
	*out = *(*config.DNSProviderControllerConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_DNSProviderControllerConfig_To_config_DNSProviderControllerConfig is an autogenerated conversion function.
func Convert_v1alpha1_DNSProviderControllerConfig_To_config_DNSProviderControllerConfig(in *DNSProviderControllerConfig, out *config.DNSProviderControllerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_DNSProviderControllerConfig_To_config_DNSProviderControllerConfig(in, out, s)
}

func autoConvert_config_DNSProviderControllerConfig_To_v1alpha1_DNSProviderControllerConfig(in *config.DNSProviderControllerConfig, out *DNSProviderControllerConfig, s conversion.Scope) error {
	*out = *(*DNSProviderControllerConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_config_DNSProviderControllerConfig_To_v1alpha1_DNSProviderControllerConfig is an autogenerated conversion function.
func Convert_config_DNSProviderControllerConfig_To_v1alpha1_DNSProviderControllerConfig(in *config.DNSProviderControllerConfig, out *DNSProviderControllerConfig, s conversion.Scope) error {
	return autoConvert_config_DNSProviderControllerConfig_To_v1alpha1_DNSProviderControllerConfig(in, out, s)
}

func autoConvert_v1alpha1_GCPWorkloadIdentityConfig_To_config_GCPWorkloadIdentityConfig(in *GCPWorkloadIdentityConfig, out *config.GCPWorkloadIdentityConfig, s conversion.Scope) error {
	*out = *(*config.GCPWorkloadIdentityConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_GCPWorkloadIdentityConfig_To_config_GCPWorkloadIdentityConfig is an autogenerated conversion function.
func Convert_v1alpha1_GCPWorkloadIdentityConfig_To_config_GCPWorkloadIdentityConfig(in *GCPWorkloadIdentityConfig, out *config.GCPWorkloadIdentityConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_GCPWorkloadIdentityConfig_To_config_GCPWorkloadIdentityConfig(in, out, s)
}

func autoConvert_config_GCPWorkloadIdentityConfig_To_v1alpha1_GCPWorkloadIdentityConfig(in *config.GCPWorkloadIdentityConfig, out *GCPWorkloadIdentityConfig, s conversion.Scope) error {
	*out = *(*GCPWorkloadIdentityConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_config_GCPWorkloadIdentityConfig_To_v1alpha1_GCPWorkloadIdentityConfig is an autogenerated conversion function.
func Convert_config_GCPWorkloadIdentityConfig_To_v1alpha1_GCPWorkloadIdentityConfig(in *config.GCPWorkloadIdentityConfig, out *GCPWorkloadIdentityConfig, s conversion.Scope) error {
	return autoConvert_config_GCPWorkloadIdentityConfig_To_v1alpha1_GCPWorkloadIdentityConfig(in, out, s)
}

func autoConvert_v1alpha1_RateLimiterOptions_To_config_RateLimiterOptions(in *RateLimiterOptions, out *config.RateLimiterOptions, s conversion.Scope) error {
	*out = *(*config.RateLimiterOptions)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_RateLimiterOptions_To_config_RateLimiterOptions is an autogenerated conversion function.
func Convert_v1alpha1_RateLimiterOptions_To_config_RateLimiterOptions(in *RateLimiterOptions, out *config.RateLimiterOptions, s conversion.Scope) error {
	return autoConvert_v1alpha1_RateLimiterOptions_To_config_RateLimiterOptions(in, out, s)
}

func autoConvert_config_RateLimiterOptions_To_v1alpha1_RateLimiterOptions(in *config.RateLimiterOptions, out *RateLimiterOptions, s conversion.Scope) error {
	*out = *(*RateLimiterOptions)(unsafe.Pointer(in))
	return nil
}

// Convert_config_RateLimiterOptions_To_v1alpha1_RateLimiterOptions is an autogenerated conversion function.
func Convert_config_RateLimiterOptions_To_v1alpha1_RateLimiterOptions(in *config.RateLimiterOptions, out *RateLimiterOptions, s conversion.Scope) error {
	return autoConvert_config_RateLimiterOptions_To_v1alpha1_RateLimiterOptions(in, out, s)
}

func autoConvert_v1alpha1_Server_To_config_Server(in *Server, out *config.Server, s conversion.Scope) error {
	*out = *(*config.Server)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_Server_To_config_Server is an autogenerated conversion function.
func Convert_v1alpha1_Server_To_config_Server(in *Server, out *config.Server, s conversion.Scope) error {
	return autoConvert_v1alpha1_Server_To_config_Server(in, out, s)
}

func autoConvert_config_Server_To_v1alpha1_Server(in *config.Server, out *Server, s conversion.Scope) error {
	*out = *(*Server)(unsafe.Pointer(in))
	return nil
}

// Convert_config_Server_To_v1alpha1_Server is an autogenerated conversion function.
func Convert_config_Server_To_v1alpha1_Server(in *config.Server, out *Server, s conversion.Scope) error {
	return autoConvert_config_Server_To_v1alpha1_Server(in, out, s)
}

func autoConvert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(in *ServerConfiguration, out *config.ServerConfiguration, s conversion.Scope) error {
	*out = *(*config.ServerConfiguration)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(in *ServerConfiguration, out *config.ServerConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_ServerConfiguration_To_config_ServerConfiguration(in, out, s)
}

func autoConvert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(in *config.ServerConfiguration, out *ServerConfiguration, s conversion.Scope) error {
	*out = *(*ServerConfiguration)(unsafe.Pointer(in))
	return nil
}

// Convert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration is an autogenerated conversion function.
func Convert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(in *config.ServerConfiguration, out *ServerConfiguration, s conversion.Scope) error {
	return autoConvert_config_ServerConfiguration_To_v1alpha1_ServerConfiguration(in, out, s)
}

func autoConvert_v1alpha1_SourceControllerConfig_To_config_SourceControllerConfig(in *SourceControllerConfig, out *config.SourceControllerConfig, s conversion.Scope) error {
	*out = *(*config.SourceControllerConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_SourceControllerConfig_To_config_SourceControllerConfig is an autogenerated conversion function.
func Convert_v1alpha1_SourceControllerConfig_To_config_SourceControllerConfig(in *SourceControllerConfig, out *config.SourceControllerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_SourceControllerConfig_To_config_SourceControllerConfig(in, out, s)
}

func autoConvert_config_SourceControllerConfig_To_v1alpha1_SourceControllerConfig(in *config.SourceControllerConfig, out *SourceControllerConfig, s conversion.Scope) error {
	*out = *(*SourceControllerConfig)(unsafe.Pointer(in))
	return nil
}

// Convert_config_SourceControllerConfig_To_v1alpha1_SourceControllerConfig is an autogenerated conversion function.
func Convert_config_SourceControllerConfig_To_v1alpha1_SourceControllerConfig(in *config.SourceControllerConfig, out *SourceControllerConfig, s conversion.Scope) error {
	return autoConvert_config_SourceControllerConfig_To_v1alpha1_SourceControllerConfig(in, out, s)
}
