//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	configv1alpha1 "k8s.io/component-base/config/v1alpha1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedOptions) DeepCopyInto(out *AdvancedOptions) {
	*out = *in
	if in.RateLimits != nil {
		in, out := &in.RateLimits, &out.RateLimits
		*out = new(RateLimiterOptions)
		**out = **in
	}
	if in.BatchSize != nil {
		in, out := &in.BatchSize, &out.BatchSize
		*out = new(int)
		**out = **in
	}
	if in.MaxRetries != nil {
		in, out := &in.MaxRetries, &out.MaxRetries
		*out = new(int)
		**out = **in
	}
	if in.BlockedZones != nil {
		in, out := &in.BlockedZones, &out.BlockedZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedOptions.
func (in *AdvancedOptions) DeepCopy() *AdvancedOptions {
	if in == nil {
		return nil
	}
	out := new(AdvancedOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientConnection) DeepCopyInto(out *ClientConnection) {
	*out = *in
	out.ClientConnectionConfiguration = in.ClientConnectionConfiguration
	if in.CacheResyncPeriod != nil {
		in, out := &in.CacheResyncPeriod, &out.CacheResyncPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientConnection.
func (in *ClientConnection) DeepCopy() *ClientConnection {
	if in == nil {
		return nil
	}
	out := new(ClientConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlPlaneClientConnection) DeepCopyInto(out *ControlPlaneClientConnection) {
	*out = *in
	out.ClientConnectionConfiguration = in.ClientConnectionConfiguration
	if in.CacheResyncPeriod != nil {
		in, out := &in.CacheResyncPeriod, &out.CacheResyncPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlPlaneClientConnection.
func (in *ControlPlaneClientConnection) DeepCopy() *ControlPlaneClientConnection {
	if in == nil {
		return nil
	}
	out := new(ControlPlaneClientConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControllerConfiguration) DeepCopyInto(out *ControllerConfiguration) {
	*out = *in
	in.DNSProvider.DeepCopyInto(&out.DNSProvider)
	in.DNSEntry.DeepCopyInto(&out.DNSEntry)
	in.DNSAnnotation.DeepCopyInto(&out.DNSAnnotation)
	in.Source.DeepCopyInto(&out.Source)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControllerConfiguration.
func (in *ControllerConfiguration) DeepCopy() *ControllerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControllerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSAnnotationControllerConfig) DeepCopyInto(out *DNSAnnotationControllerConfig) {
	*out = *in
	if in.ConcurrentSyncs != nil {
		in, out := &in.ConcurrentSyncs, &out.ConcurrentSyncs
		*out = new(int)
		**out = **in
	}
	if in.SkipNameValidation != nil {
		in, out := &in.SkipNameValidation, &out.SkipNameValidation
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSAnnotationControllerConfig.
func (in *DNSAnnotationControllerConfig) DeepCopy() *DNSAnnotationControllerConfig {
	if in == nil {
		return nil
	}
	out := new(DNSAnnotationControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSEntryControllerConfig) DeepCopyInto(out *DNSEntryControllerConfig) {
	*out = *in
	if in.ConcurrentSyncs != nil {
		in, out := &in.ConcurrentSyncs, &out.ConcurrentSyncs
		*out = new(int)
		**out = **in
	}
	if in.SyncPeriod != nil {
		in, out := &in.SyncPeriod, &out.SyncPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxConcurrentLookups != nil {
		in, out := &in.MaxConcurrentLookups, &out.MaxConcurrentLookups
		*out = new(int)
		**out = **in
	}
	if in.DefaultCNAMELookupInterval != nil {
		in, out := &in.DefaultCNAMELookupInterval, &out.DefaultCNAMELookupInterval
		*out = new(int64)
		**out = **in
	}
	if in.ReconciliationDelayAfterUpdate != nil {
		in, out := &in.ReconciliationDelayAfterUpdate, &out.ReconciliationDelayAfterUpdate
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SkipNameValidation != nil {
		in, out := &in.SkipNameValidation, &out.SkipNameValidation
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSEntryControllerConfig.
func (in *DNSEntryControllerConfig) DeepCopy() *DNSEntryControllerConfig {
	if in == nil {
		return nil
	}
	out := new(DNSEntryControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSManagerConfiguration) DeepCopyInto(out *DNSManagerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.ClientConnection != nil {
		in, out := &in.ClientConnection, &out.ClientConnection
		*out = new(ClientConnection)
		(*in).DeepCopyInto(*out)
	}
	if in.ControlPlaneClientConnection != nil {
		in, out := &in.ControlPlaneClientConnection, &out.ControlPlaneClientConnection
		*out = new(ControlPlaneClientConnection)
		(*in).DeepCopyInto(*out)
	}
	in.LeaderElection.DeepCopyInto(&out.LeaderElection)
	in.Server.DeepCopyInto(&out.Server)
	if in.Debugging != nil {
		in, out := &in.Debugging, &out.Debugging
		*out = new(configv1alpha1.DebuggingConfiguration)
		(*in).DeepCopyInto(*out)
	}
	in.Controllers.DeepCopyInto(&out.Controllers)
	if in.ProviderAdvancedOptions != nil {
		in, out := &in.ProviderAdvancedOptions, &out.ProviderAdvancedOptions
		*out = make(map[string]AdvancedOptions, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSManagerConfiguration.
func (in *DNSManagerConfiguration) DeepCopy() *DNSManagerConfiguration {
	if in == nil {
		return nil
	}
	out := new(DNSManagerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSManagerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSProviderControllerConfig) DeepCopyInto(out *DNSProviderControllerConfig) {
	*out = *in
	if in.ConcurrentSyncs != nil {
		in, out := &in.ConcurrentSyncs, &out.ConcurrentSyncs
		*out = new(int)
		**out = **in
	}
	if in.SyncPeriod != nil {
		in, out := &in.SyncPeriod, &out.SyncPeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.EnabledProviderTypes != nil {
		in, out := &in.EnabledProviderTypes, &out.EnabledProviderTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisabledProviderTypes != nil {
		in, out := &in.DisabledProviderTypes, &out.DisabledProviderTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultRateLimits != nil {
		in, out := &in.DefaultRateLimits, &out.DefaultRateLimits
		*out = new(RateLimiterOptions)
		**out = **in
	}
	if in.DefaultTTL != nil {
		in, out := &in.DefaultTTL, &out.DefaultTTL
		*out = new(int64)
		**out = **in
	}
	if in.ZoneCacheTTL != nil {
		in, out := &in.ZoneCacheTTL, &out.ZoneCacheTTL
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AllowMockInMemoryProvider != nil {
		in, out := &in.AllowMockInMemoryProvider, &out.AllowMockInMemoryProvider
		*out = new(bool)
		**out = **in
	}
	if in.SkipNameValidation != nil {
		in, out := &in.SkipNameValidation, &out.SkipNameValidation
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSProviderControllerConfig.
func (in *DNSProviderControllerConfig) DeepCopy() *DNSProviderControllerConfig {
	if in == nil {
		return nil
	}
	out := new(DNSProviderControllerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimiterOptions) DeepCopyInto(out *RateLimiterOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimiterOptions.
func (in *RateLimiterOptions) DeepCopy() *RateLimiterOptions {
	if in == nil {
		return nil
	}
	out := new(RateLimiterOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Server) DeepCopyInto(out *Server) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Server.
func (in *Server) DeepCopy() *Server {
	if in == nil {
		return nil
	}
	out := new(Server)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerConfiguration) DeepCopyInto(out *ServerConfiguration) {
	*out = *in
	out.Webhooks = in.Webhooks
	if in.HealthProbes != nil {
		in, out := &in.HealthProbes, &out.HealthProbes
		*out = new(Server)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(Server)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerConfiguration.
func (in *ServerConfiguration) DeepCopy() *ServerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ServerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceControllerConfig) DeepCopyInto(out *SourceControllerConfig) {
	*out = *in
	if in.ConcurrentSyncs != nil {
		in, out := &in.ConcurrentSyncs, &out.ConcurrentSyncs
		*out = new(int)
		**out = **in
	}
	if in.TargetClass != nil {
		in, out := &in.TargetClass, &out.TargetClass
		*out = new(string)
		**out = **in
	}
	if in.TargetNamespace != nil {
		in, out := &in.TargetNamespace, &out.TargetNamespace
		*out = new(string)
		**out = **in
	}
	if in.TargetNamePrefix != nil {
		in, out := &in.TargetNamePrefix, &out.TargetNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.TargetClusterID != nil {
		in, out := &in.TargetClusterID, &out.TargetClusterID
		*out = new(string)
		**out = **in
	}
	if in.SourceClusterID != nil {
		in, out := &in.SourceClusterID, &out.SourceClusterID
		*out = new(string)
		**out = **in
	}
	if in.DNSProviderReplication != nil {
		in, out := &in.DNSProviderReplication, &out.DNSProviderReplication
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceControllerConfig.
func (in *SourceControllerConfig) DeepCopy() *SourceControllerConfig {
	if in == nil {
		return nil
	}
	out := new(SourceControllerConfig)
	in.DeepCopyInto(out)
	return out
}
