//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: SAP SE or an SAP affiliate company and Gardener contributors
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&DNSManagerConfiguration{}, func(obj interface{}) { SetObjectDefaults_DNSManagerConfiguration(obj.(*DNSManagerConfiguration)) })
	return nil
}

func SetObjectDefaults_DNSManagerConfiguration(in *DNSManagerConfiguration) {
	SetDefaults_DNSManagerConfiguration(in)
	if in.ClientConnection != nil {
		SetDefaults_ClientConnection(in.ClientConnection)
	}
	if in.ControlPlaneClientConnection != nil {
		SetDefaults_ControlPlaneClientConnection(in.ControlPlaneClientConnection)
	}
	SetDefaults_LeaderElectionConfiguration(&in.LeaderElection)
	SetDefaults_ServerConfiguration(&in.Server)
	SetDefaults_DNSProviderControllerConfig(&in.Controllers.DNSProvider)
}
