// SPDX-FileCopyrightText: Contributors to the Gardener project
//
// SPDX-License-Identifier: Apache-2.0
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/gardener/external-dns-management/pkg/client/dns/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// DNSAnnotations returns a DNSAnnotationInformer.
	DNSAnnotations() TypedDNSAnnotationInformer
	// DNSEntries returns a DNSEntryInformer.
	DNSEntries() TypedDNSEntryInformer
	// DNSHostedZonePolicies returns a DNSHostedZonePolicyInformer.
	DNSHostedZonePolicies() TypedDNSHostedZonePolicyInformer
	// DNSProviders returns a DNSProviderInformer.
	DNSProviders() TypedDNSProviderInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// DNSAnnotations returns a TypedDNSAnnotationInformer.
func (v *version) DNSAnnotations() TypedDNSAnnotationInformer {
	return &dNSAnnotationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DNSEntries returns a TypedDNSEntryInformer.
func (v *version) DNSEntries() TypedDNSEntryInformer {
	return &dNSEntryInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DNSHostedZonePolicies returns a TypedDNSHostedZonePolicyInformer.
func (v *version) DNSHostedZonePolicies() TypedDNSHostedZonePolicyInformer {
	return &dNSHostedZonePolicyInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DNSProviders returns a TypedDNSProviderInformer.
func (v *version) DNSProviders() TypedDNSProviderInformer {
	return &dNSProviderInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
